version: "3.9"

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
    image: vault-with-myengine:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_PLUGIN_NAME: myengine
      VAULT_PLUGIN_PATH: /etc/vault/plugins/myengine
      VAULT_MOUNT_PATH: myengine
      BUCKET_SUFFIX: my-bucket
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
    networks:
      - project-net

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,iam,sts
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    networks:
      - project-net
    volumes:
      - ./init:/docker-entrypoint-initaws.d
      - ./localstack-data:/var/lib/localstack
      - ./aws:/root/.aws

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
    container_name: terraform
    networks:
      - project-net
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    working_dir: /workspace
    volumes:
      - ./terraform-localstack:/workspace:rw
    stdin_open: true
    tty: true

volumes:
  vault-data:
  jobs:

networks:
  project-net:
    driver: bridge
