version: "3.9"

services:
  nomad:
    image: hashicorp/nomad:1.8.0
    container_name: nomad
    command: agent -dev -bind=0.0.0.0
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"
    networks:
      - project-net
    volumes:
      - ./jobs:/jobs

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,iam
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    networks:
      - project-net
    volumes:
      - ./init:/docker-entrypoint-initaws.d
      - ./localstack-data:/var/lib/localstack
      - ./aws:/root/.aws

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
    container_name: terraform
    networks:
      - project-net
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    working_dir: /workspace
    volumes:
      - ./terraform-localstack:/workspace:rw
    stdin_open: true
    tty: true

networks:
  project-net:
    driver: bridge
